export const maps = [
    "Azarov's Resting Place",
    "Badham Preschool I",
    "Badham Preschool II",
    "Badham Preschool III",
    "Badham Preschool IV",
    "Badham Preschool V",
    "Badham Preschools",
    "Blood Lodge",
    "Coal Tower",
    "Dead Dawg Saloon",
    "Disturbed Ward",
    "Eyrie of Crows",
    "Family Residence",
    "Father Campbell's Chapel",
    "Fractured Cowshed",
    "Garden of Joy",
    "Gas Heaven",
    "Grim Pantry",
    "Groaning Storehouse",
    "Ironworks of Misery",
    "Lampkin Lane",
    "Midwich Elementary School",
    "Mother's Dwelling",
    "Mount Ormond Resort",
    "Raccoon City Police Station",
    "Raccoon City Police Station East Wing",
    "Raccoon City Police Station West Wing",
    "Rancid Abattoir",
    "Rotten Fields",
    "Sanctum of Wrath",
    "Shelter Woods",
    "Suffocation Pit",
    "The Game",
    "The Pale Rose",
    "The Shattered Square",
    "The Temple of Purgation",
    "The Thompson House",
    "The Underground Complex",
    "Torment Creek",
    "Treatment Theatre",
    "Wrecker's Yard",
    "Wretched Shop"
]
export const killers = [
    "Artist",
    "Blight",
    "Cannibal",
    "Cenobite",
    "Clown",
    "Demo",
    "Doctor",
    "Dredge",
    "Freddy Krueger",
    "Ghost Face",
    "Gunslinger",
    "Hag",
    "Hillbilly",
    "Huntress",
    "Knight",
    "Legion",
    "Myers",
    "Nemesis",
    "Nurse",
    "Oni",
    "Onryo",
    "Pig",
    "Plague",
    "Pyramid Head",
    "Spirit",
    "Trapper",
    "Trickster",
    "Twins",
    "Wesker",
    "Wraith"
]
export const survivors = [
    "Ace Visconti",
    "Ada Wong",
    "Adam Francis",
    "Ashley J. Williams",
    "Cheryl Mason",
    "Claudette Morel",
    "David King",
    "Detective David Tapp",
    "Dwight Fairfield",
    "Elodie Rakoto",
    "Felix Richter",
    "Feng Min",
    "Haddie Kaur",
    "Jake Park",
    "Jane Romero",
    "Jeffrey 'Jeff' Johansen",
    "Jill Valentine",
    "Jonah Vasquez",
    "Kate Denson",
    "Laurie Strode",
    "Leon Scott Kennedy",
    "Meg Thomas",
    "Mikaela Reid",
    "Nancy Wheeler",
    "Nea Karlsson",
    "Quentin Smith",
    "Rebecca Chambers",
    "Steve Harrington",
    "Vittorio Toscano",
    "William 'Bill' Overbeck",
    "Yoichi Asakawa",
    "Yui Kimura",
    "Yun-Jin Lee",
    "Zarina Kassir"
]